# Generated by Django 5.2.8 on 2025-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1SuiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='c1SuiteApp.permissao'),
        ),
    ]
