# Generated by Django 5.2.8 on 2025-12-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1SuiteApp', '0002_perfil_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceiroTipo',
            fields=[
                ('id_tipopar', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Parceiro',
                'verbose_name_plural': 'Tipos de Parceiro',
                'db_table': 'parceiros_tipo',
            },
        ),
    ]
