# Generated by Django 5.2.8 on 2025-12-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1SuiteApp', '0003_parceirotipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uf',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('id_ibge', models.CharField(max_length=10)),
                ('uf', models.ForeignKey(db_column='uf', on_delete=django.db.models.deletion.PROTECT, to='c1SuiteApp.uf')),
            ],
            options={
                'db_table': 'cidades',
            },
        ),
    ]
