# Generated by Django 5.2.8 on 2025-12-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1SuiteApp', '0004_uf_cidade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cidade',
            table='c1SuiteApp_cidades',
        ),
        migrations.AlterModelTable(
            name='uf',
            table='c1SuiteApp_uf',
        ),
    ]
